# Generated by Django 4.0.6 on 2022-08-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0002_rename_points_reward_loyalty_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='account',
        ),
    ]
