# Generated by Django 4.1.1 on 2022-09-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0002_remove_receipt_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='wallet',
        ),
    ]
