# Generated by Django 4.1.1 on 2022-09-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0003_remove_account_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='date',
            new_name='receipt_date',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='receipt_number',
            new_name='receipt_num',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='receipt_type',
            new_name='receipt_types',
        ),
    ]
